version: "3"

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: twitterdb
      MYSQL_USER: user
      MYSQL_PASSWORD: 'pwd'
      MARIADB_ROOT_PASSWORD: 'rootpwd'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  pma:
    image: phpmyadmin/phpmyadmin
    ports: 
      - 8123:80
    environment:
      PMA_HOST: db
      PMA_USER: 'user'
      PMA_PASSWORD: 'pwd'

  server:
    build: ./server
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      DB_HOST: db
  client:
    build: ./client
    ports:
      - "3000:3000"
